[package]
name = "session"
version = "0.1.0"
authors = ["jarryliu <jarrysix@gmail.com>"]
edition = "2018"

[dependencies]
typemap = "~0.3"
uuid = { version = "~0.7", features = ["v4"] }
md5 = "~0.6.1"
